services:
  mc-tester:
    user: "0:0"
    container_name: mc-tester
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR" # Server type i'm currently using
      ONLINE_MODE: "FALSE"
      MEMORY: "3G"
    volumes:
      - ./plugins:/data/plugins # Scan from what folder and file 