name: Server Automatic Deploy

on:
  push:
    branches:
      - main

env:
  SERVER_PATH: "/home/timmylionel/minecraft-docker"

jobs:
  ship-it:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to GCP (Manual Mode)
        run: |
          # 1. Create a temporary file for the key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          
          # 2. Run the actual rsync command
          rsync -avzr --delete \
            -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.GCP_USER }}@${{ secrets.GCP_IP }}:${{ env.SERVER_PATH }}
            
          # 3. Clean up the key
          rm private_key

      - name: Reload Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_strict: false
          script: |
            cd ${{ env.SERVER_PATH }}
            docker-compose up -d --remove-orphans