name: Plugin Test Pipelines # To check if plugin is compatible or is there any error lines
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Testing Server
        run: docker compose -f docker-compose-testing.yml up -d

      - name: Log Inspection
        run: |
          echo "Initializing docker... and Taking a breath :]"
          sleep 10
          
          # Check if the container is even running
          if ! docker ps | grep -q "mc-tester"; then
            echo "Oh noes! Container failed to start! Here is the logs for debugging:"
            docker compose -f docker-compose-testing.yml logs
            exit 1
          fi

          echo "Waiting for server to boot..."
          # This follows the logs until the Done appears, with a 3 minute timeout to let the server boot
          timeout 180s stdbuf -oL docker logs -f mc-tester | grep -m 1 "Done"
          
          if [ $? -eq 0 ]; then
            echo "Yay! Server reached 'Done' state!"
          else
            echo "Oh no! Server timed out or crashed before Done."
            docker logs mc-tester
            exit 1
          fi