name: Plugin Test Pipelines # To check if plugin is compatible or is there any error lines

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Testing Server
        run: docker compose -f docker-compose-testing.yml up -d

      - name: Log Inspection & Error Scan
        run: |
          sudo chown -R $USER:$USER ./plugins
          set +e  # Basically Tell the script not to quit if a grep finds nothing it's just set exit
          
          echo "Waiting for server to boot..."
          timeout 180s stdbuf -oL docker logs -f mc-tester | grep -m 1 "Done"
          
          if [ $? -ne 0 ]; then
            echo "Oh noes! Server timed out or crashed."
            docker logs mc-tester | tail -n 20
            exit 1
          fi

          echo "Plase be patient sir! Scanning for critical failures..."
          # Searching for Errors, but ignore common fake errors if they exist
          ERRORS=$(docker logs mc-tester | grep -Ei "Error|Exception|Severe" | grep -v "VersionCheck")

          if [ ! -z "$ERRORS" ]; then
            echo "Oh no! Test Failed: Found critical errors!"
            echo "$ERRORS"
            exit 1
          else
            echo "Yay! Log scan clean! No critical issues found."
          fi